---
galaxy_info:
  role_name: docker_engine
  author: Denis
  description: Install Docker Engine and Docker Compose v2 plugin
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["jammy", "noble"]
    - name: Debian
      versions: ["bullseye", "bookworm"]
dependencies: []