---
galaxy_info:
  role_name: nginx_compose
  author: Denis
  description: Deploy nginx using docker compose v2
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["jammy", "noble"]
    - name: Debian
      versions: ["bullseye", "bookworm"]
dependencies: []